name: CI

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  test-chrome:
    runs-on: windows-latest
    strategy:
      matrix:
        chrome: ['913920']
    name: Chrome Browser Tests
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Setup Chrome ${{ matrix.chrome }}
        uses: browser-actions/setup-chrome@latest
        with:
          chrome-version: ${{ matrix.chrome }}
      - name: npm install
        run: npm install
      #- name: npm run build
      #  run: npm run build
      - name: npm run test
        run: npm run test
        env:
          CI_BROWSER: C:\hostedtoolcache\windows\chromium\${{ matrix.chrome }}\x64\chrome.exe
          CI_BROWSER_FLAGS: 
